### ISSUE TITLE
:data prop not reactive

### ISSUE THREAD

**Issue by DaxChen** [lineupjs/vue-lineup#1]
* Release number or git hash: vue-lineup: 1.0.7
 * Web browser version and OS: Chrome 73.0.3683.103 64bit on macOS

### Steps to reproduce

 1. render `<LineUp :data="data" />`
 1. change data, LineUp does not reactive update new data

The use case could be the data is fetched from backend, or changes based on user settings, so the data would change.

### Observed behavior
 * No errors or warnings, just nothing happens when data changes.

### Expected behavior
 * LineUp chart reactively re-renders with the new data.

I see that in LineUp.vue, in the updated() hook, it only detects if things in IBuilderAdapterProps has changed, but not data.

Maybe could add a vue watch: data to detect and act on data changes?

**Comment by sgratzl** [comment]
thx for reporting will take a look at it

**Comment by sgratzl** [comment]
@DaxChen can you elaborate how you changed the data. I created a simple test case and when I push some extra rows in the same data object, like after a couple of seconds. Vue.js will detect it and LineUp acts accordingly. Since LineUp already watches the "data" property as all other properties.

**Comment by DaxChen** [comment]
I modified the minimum example codepen

https://codepen.io/DaxChen/pen/NmzQjm

You can see from the very last part of the script, I set the data from `[]` to `data`.

This use case might be the data is fetched from an API, so initially it is set to `[]`, when the API fetch returns, the data is then set.

**Comment by sgratzl** [comment]
Hi, 
I just released v1.1.0 fixing the bug. Thx for reporting. It turned out while the watcher exists, the component didn't update itself thus the changes weren't applied.

https://codepen.io/sgratzl/pen/BEqpqp now uses the v1.1.0 version and it works as expected
