### ISSUE TITLE
vue cli compatible

### ISSUE THREAD

**Issue by WeiShengv99** [lineupjs/vue-lineup#8]
* Release number or git hash: 
 * Web browser version and OS: 

### Steps to reproduce

 1. vue cli build

### Observed behavior
normal render

### Expected behavior
 * LineUpNumberColumnDesc  cant work
but when i use
"dev-build": "vue-cli-service build --mode development",
this case ， LineUpNumberColumnDesc   can work

**Comment by sgratzl** [comment]
closing: project is being archived
